spring:
  application:
    name: stray-dogcare-backend
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/straydog}
      auto-index-creation: true
  
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:15MB}
  
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    protocol: ${SPRING_MAIL_PROTOCOL:smtp}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}

server:
  port: ${SERVER_PORT:5000}
  error:
    include-message: always
    include-binding-errors: always

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${JWT_EXPIRATION:86400000}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}
  
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}
  
  upload:
    dir: ${UPLOAD_DIR:./uploads}

file:
  upload-dir: ${FILE_UPLOAD_DIR:./uploads}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.straydogcare: ${LOGGING_LEVEL_APP:DEBUG}
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.apache.catalina.connector.ClientAbortException: ERROR
